import {FormEvent, useState} from "react";
import {useMutation, useQuery} from "@tanstack/react-query";
import {CheckCircle2, Save} from "lucide-react";
import {inventoryApi} from "../../services/inventoryApi";
import {masterDataApi} from "../../services/masterDataApi";
import {ErrorBanner, Loading} from "../../components/feedback/States";
import {errorMessage} from "../../utils/errors";
import type {InboundReceipt} from "../../types/api";

export function InboundReceivingPage(){
  const [warehouseId,setWarehouseId]=useState(""); const [receipt,setReceipt]=useState<InboundReceipt>(); const [error,setError]=useState<unknown>();
  const medicines=useQuery({queryKey:["medicines"],queryFn:()=>masterDataApi.medicines()});
  const suppliers=useQuery({queryKey:["suppliers"],queryFn:()=>masterDataApi.suppliers()});
  const warehouses=useQuery({queryKey:["warehouses"],queryFn:()=>masterDataApi.warehouses()});
  const storage=useQuery({queryKey:["storage",warehouseId],queryFn:()=>masterDataApi.storageLocations(warehouseId),enabled:!!warehouseId});
  const mutation=useMutation({mutationFn:({body,key}:{body:unknown;key:string})=>inventoryApi.inbound(body,key).then(r=>r.data as InboundReceipt),onSuccess:r=>{setReceipt(r);setError(undefined)},onError:setError});
  function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const d=new FormData(e.currentTarget);mutation.mutate({key:crypto.randomUUID(),body:{supplierId:d.get("supplierId"),warehouseId:d.get("warehouseId"),storageLocationId:d.get("storageLocationId"),medicineId:d.get("medicineId"),batchNumber:d.get("batchNumber"),manufacturingDate:d.get("manufacturingDate"),expiryDate:d.get("expiryDate"),quantity:Number(d.get("quantity"))}})}
  if(medicines.isLoading||suppliers.isLoading||warehouses.isLoading)return <Loading/>;
  if(medicines.isError||suppliers.isError||warehouses.isError)return <ErrorBanner message={errorMessage(medicines.error??suppliers.error??warehouses.error)}/>;
  return <section className="max-w-4xl"><div className="mb-6"><h1 className="text-2xl font-semibold text-ink">Inbound receiving</h1><p className="text-muted">Creates the batch, active balance, balanced receipt journal, and audit record in one atomic operation.</p></div>{receipt&&<div role="status" className="mb-4 rounded border border-success/30 bg-green-50 p-4 text-success"><div className="flex gap-2 font-medium"><CheckCircle2 size={18}/>Receipt posted</div><p className="mt-1 text-sm">Journal {receipt.journalEntryNumber}; available quantity is now {receipt.availableQuantity}.</p></div>}<form onSubmit={submit} className="grid gap-4 rounded-lg border border-border bg-canvas p-5 shadow-sm md:grid-cols-2"><label className="grid gap-1 font-medium">Supplier<select name="supplierId" required className="input"><option value="">Select supplier</option>{suppliers.data?.content.map(s=><option key={s.id} value={s.id}>{s.code} — {s.name}</option>)}</select></label><label className="grid gap-1 font-medium">Medicine<select name="medicineId" required className="input"><option value="">Select medicine</option>{medicines.data?.content.filter(x=>x.status==="ACTIVE").map(x=><option key={x.id} value={x.id}>{x.sku} — {x.genericName}</option>)}</select></label><label className="grid gap-1 font-medium">Receiving warehouse<select name="warehouseId" required value={warehouseId} onChange={e=>setWarehouseId(e.target.value)} className="input"><option value="">Select warehouse</option>{warehouses.data?.content.filter(x=>x.status==="ACTIVE").map(x=><option key={x.id} value={x.id}>{x.code} — {x.name}</option>)}</select></label><label className="grid gap-1 font-medium">Storage location<select name="storageLocationId" required disabled={!warehouseId||storage.isLoading} className="input"><option value="">{storage.isLoading?"Loading locations…":"Select location"}</option>{storage.data?.map(x=><option key={x.id} value={x.id}>{x.binCode}</option>)}</select></label><label className="grid gap-1 font-medium">Batch number<input name="batchNumber" required className="input"/></label><label className="grid gap-1 font-medium">Quantity<input name="quantity" required type="number" min="1" className="input"/></label><label className="grid gap-1 font-medium">Manufacturing date<input name="manufacturingDate" required type="date" className="input"/></label><label className="grid gap-1 font-medium">Expiry date<input name="expiryDate" required type="date" className="input"/></label><div className="md:col-span-2">{error?<ErrorBanner message={errorMessage(error)}/>:null}<button type="submit" disabled={mutation.isPending} className="inline-flex min-h-10 items-center gap-2 rounded bg-ink px-4 font-medium text-white disabled:opacity-50"><Save size={16}/>{mutation.isPending?"Posting receipt…":"Post inbound receipt"}</button></div></form></section>
}
